version: "3"
services:
  dynamodb-local:
    image: cnadiminti/dynamodb-local
    ports:
      - 8000:8000
    volumes:
      - ./.database:/dynamodb_local_db

  dynamodb-admin:
    image: manhvu2507/dynamodb-admin-docker
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
    ports:
      - 8001:8001
